DEV-31962
Unact/oauth-service pull request #2
Opened 2016-12-13 13:29 UTC by DCrow

2016-12-13 20:15 UTC, kurtov commented
Ярослав, что же ты так время своих коллег не ценишь. Новый PR и опять 70+ файлов. Тут жу явно не все надо смотреть.

2016-12-13 20:41 UTC, DCrow commented
PR новый потому что старый почему то закрылся
А смотреть можно все начиная от коммита 82113ab

2016-12-13 21:02 UTC, kurtov requested changes

2016-12-13 21:02 UTC, kurtov commented on app/controllers/concerns/oauth_service/controller.rb
> +        @user_update_fails += 1
Плохая идея использовать в качестве счетчика попыток переменную экземпляра. переделай на локальную (переделай на цикл в retry/redo или передавай номер попытки в `update_user_access_token`)

2016-12-13 21:02 UTC, kurtov commented on app/controllers/concerns/oauth_service/controller.rb
> +          :data => {},
`:data => {},` - нигде не используется

2016-12-13 21:02 UTC, kurtov commented on app/controllers/concerns/oauth_service/controller.rb
> +        unless @user_info[:error]
unless с else не используют, см code-stype

2016-12-13 21:02 UTC, kurtov commented on spec/controllers/base_controller_spec.rb
> +      it "doesnt update token" do
У меня сложилось впечатление, поэтому могу и ошибаться, что прочитав последовательно
describe, context и it я должен получить наполненное смыслом и истинное утверждение. Здесь же получается два противоположных утверждения.

2016-12-13 21:02 UTC, kurtov commented on spec/helpers/spec_helper.rb
> +Rails.backtrace_cleaner.remove_silencers!
что бы это значило...

2016-12-13 21:07 UTC, kurtov commented
> старый почему то закрылся

Кто-то похерил последний коммит в мастере вот он и закрылся (в PR 0 коммитов)

2016-12-13 21:36 UTC, DCrow commented on spec/helpers/spec_helper.rb
> +Rails.backtrace_cleaner.remove_silencers!
http://api.rubyonrails.org/classes/ActiveSupport/BacktraceCleaner.html#method-i-remove_silencers-21

2016-12-13 21:38 UTC, DCrow commented on spec/controllers/base_controller_spec.rb
> +      it "doesnt update token" do
Получаем BaseController update_user_access_token(название метода в контроллере) doesnt update token

Почему оно противоположное? Может стоит дописать method в context(он кстати является алиасом describe)

2016-12-13 21:39 UTC, DCrow commented
А, вот почему он закрылся.

2016-12-13 21:45 UTC, kurtov commented on spec/controllers/base_controller_spec.rb
> +      it "doesnt update token" do
`login_user update_user_access_token updates token`
`login_user update_user_access_token doesnt update token`

2016-12-14 08:15 UTC, DCrow commented
Поправил

2016-12-14 08:57 UTC, kurtov commented on app/controllers/concerns/oauth_service/controller.rb
> +        retry_count = 0
Здесь люди делают тоже самое. 
http://blog.mirthlab.com/2012/05/25/cleanly-retrying-blocks-of-code-after-an-exception-in-ruby/

Если считаешь, что у них это написано поприятнее - можешь исправить.

2016-12-14 08:57 UTC, kurtov commented on spec/controllers/base_controller_spec.rb
> +      it "doesn't update token" do
Имеем два исключающих друг друга утверждения:
- login_user update_user_access_token updates token
- login_user update_user_access_token doesn't update token

Похоже, ты не разделяешь мою точку зрения о наполненных смыслом предложениях. Ладно, оставим это до прояснения как правильно писать названия в rspec.

2016-12-14 08:57 UTC, kurtov approved these changes

2016-12-14 08:58 UTC, kurtov commented
ok

2016-12-14 10:13 UTC, merged